const PERMISSIONS = [
  { code: 'trackable:create', category: 'trackable', description: 'Create trackables' },
  { code: 'trackable:read', category: 'trackable', description: 'View trackables' },
  { code: 'trackable:update', category: 'trackable', description: 'Edit trackables' },
  { code: 'trackable:delete', category: 'trackable', description: 'Delete trackables' },
  { code: 'workflow_item:create', category: 'workflow', description: 'Create workflow items' },
  { code: 'workflow_item:read', category: 'workflow', description: 'View workflow items' },
  { code: 'workflow_item:update', category: 'workflow', description: 'Edit workflow items' },
  { code: 'workflow_item:delete', category: 'workflow', description: 'Delete workflow items' },
  { code: 'document:create', category: 'document', description: 'Create documents' },
  { code: 'document:read', category: 'document', description: 'View documents' },
  { code: 'document:update', category: 'document', description: 'Edit documents' },
  { code: 'document:delete', category: 'document', description: 'Delete documents' },
  { code: 'folder:create', category: 'folder', description: 'Create folders' },
  { code: 'folder:read', category: 'folder', description: 'View folders' },
  { code: 'folder:update', category: 'folder', description: 'Edit folders' },
  { code: 'folder:delete', category: 'folder', description: 'Delete folders' },
  { code: 'user:create', category: 'user', description: 'Create users' },
  { code: 'user:read', category: 'user', description: 'View users' },
  { code: 'user:update', category: 'user', description: 'Edit users' },
  { code: 'user:delete', category: 'user', description: 'Delete users' },
  { code: 'workflow:assign', category: 'workflow_action', description: 'Assign workflow items' },
  { code: 'workflow:review', category: 'workflow_action', description: 'Review submitted items' },
  { code: 'workflow:validate', category: 'workflow_action', description: 'Validate reviewed items' },
  { code: 'workflow:close', category: 'workflow_action', description: 'Close validated items' },
  { code: 'workflow:reject', category: 'workflow_action', description: 'Reject items' },
  { code: 'workflow:skip', category: 'workflow_action', description: 'Skip workflow items' },
  { code: 'org:manage', category: 'system', description: 'Manage organization settings' },
  { code: 'role:manage', category: 'system', description: 'Manage roles and permissions' },
  { code: 'scraping:trigger', category: 'system', description: 'Trigger on-demand scraping' },
];

export { PERMISSIONS };
