const PERMISSIONS = [
  { code: 'trackable:create', category: 'trackable', description: 'Create trackables' },
  { code: 'trackable:read', category: 'trackable', description: 'View trackables' },
  { code: 'trackable:update', category: 'trackable', description: 'Edit trackables' },
  {
    code: 'trackable_view:share',
    category: 'trackable',
    description: 'Share saved expedientes list views with the organization',
  },
  { code: 'workflow_item:create', category: 'workflow', description: 'Create workflow items' },
  { code: 'workflow_item:read', category: 'workflow', description: 'View workflow items' },
  { code: 'workflow_item:update', category: 'workflow', description: 'Edit workflow items' },
  { code: 'workflow_item:delete', category: 'workflow', description: 'Delete workflow items' },
  { code: 'workflow_item:comment', category: 'workflow', description: 'Comment on workflow items' },
  { code: 'document:create', category: 'document', description: 'Create documents' },
  { code: 'document:read', category: 'document', description: 'View documents' },
  { code: 'document:update', category: 'document', description: 'Edit documents' },
  { code: 'document:delete', category: 'document', description: 'Delete documents' },
  { code: 'folder:create', category: 'folder', description: 'Create folders' },
  { code: 'folder:read', category: 'folder', description: 'View folders' },
  { code: 'folder:update', category: 'folder', description: 'Edit folders' },
  { code: 'folder:delete', category: 'folder', description: 'Delete folders' },
  { code: 'user:create', category: 'user', description: 'Create users' },
  { code: 'user:read', category: 'user', description: 'View users' },
  { code: 'user:update', category: 'user', description: 'Edit users' },
  { code: 'user:delete', category: 'user', description: 'Delete users' },
  { code: 'workflow:assign', category: 'workflow_action', description: 'Assign workflow items' },
  { code: 'workflow:review', category: 'workflow_action', description: 'Review submitted items' },
  { code: 'workflow:validate', category: 'workflow_action', description: 'Validate reviewed items' },
  { code: 'workflow:close', category: 'workflow_action', description: 'Close validated items' },
  { code: 'workflow:reject', category: 'workflow_action', description: 'Reject items' },
  { code: 'workflow:skip', category: 'workflow_action', description: 'Skip workflow items' },
  { code: 'workflow:update', category: 'workflow_action', description: 'Manage workflow definitions (states and transitions)' },
  { code: 'org:manage', category: 'system', description: 'Manage organization settings' },
  { code: 'role:manage', category: 'system', description: 'Manage roles and permissions' },
  { code: 'scraping:trigger', category: 'system', description: 'Trigger on-demand scraping' },
  {
    code: 'sinoe:manage',
    category: 'integration',
    description: 'Configure SINOE credentials and sync notifications',
  },
  { code: 'calendar:read', category: 'calendar', description: 'View organization calendar' },
  { code: 'calendar:view_team', category: 'calendar', description: 'View team calendar scope' },
  {
    code: 'calendar:integration:manage',
    category: 'calendar',
    description: 'Connect Google/Outlook calendar',
  },
  { code: 'billing:read', category: 'billing', description: 'View plan, billing and AI credits' },
  { code: 'billing:manage', category: 'billing', description: 'Change plan, payment methods and credit allocations' },
  {
    code: 'import:manage',
    category: 'import',
    description: 'Run data imports / migration batches for the organization',
  },
  {
    code: 'whatsapp:use_assistant',
    category: 'whatsapp',
    description: 'Use the AI assistant over WhatsApp',
  },
  {
    code: 'whatsapp:send_to_self',
    category: 'whatsapp',
    description: 'Allow assistant to send messages or links to own WhatsApp',
  },
  {
    code: 'whatsapp:send_to_others',
    category: 'whatsapp',
    description: 'Allow assistant to message other org members via WhatsApp',
  },
  {
    code: 'whatsapp:receive_notifications',
    category: 'whatsapp',
    description: 'Receive calendar and in-app notification digests via WhatsApp',
  },
  { code: 'blueprint:read', category: 'blueprint', description: 'View blueprints and resolved structure' },
  { code: 'blueprint:manage', category: 'blueprint', description: 'Adopt, edit, publish tenant blueprints and overrides' },
  {
    code: 'sinoe-proposal:approve',
    category: 'integration',
    description: 'Approve or reject SINOE proposal actions',
  },
  { code: 'feed:read', category: 'feed', description: 'View legal news and Alega updates feed' },
  { code: 'feed:manage', category: 'feed', description: 'Manage feed items and RSS sources' },
  { code: 'signature:create', category: 'signature', description: 'Crear solicitudes de firma' },
  { code: 'signature:sign', category: 'signature', description: 'Firmar documentos propios' },
  { code: 'signature:view_all', category: 'signature', description: 'Ver todas las solicitudes del workspace' },
  { code: 'signature:cancel', category: 'signature', description: 'Cancelar solicitudes de firma' },
  {
    code: 'signature:manage_profiles',
    category: 'signature',
    description: 'Gestionar perfiles de firma del equipo',
  },
];

export { PERMISSIONS };
